# coding: utf-8


# This file was *autogenerated* from the file ./code_uni/lab2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)#SageMath version 8.8, Python 2.7.15

from copy import copy

def init_func():
	a, b, p = map(int, raw_input('Print a, b, p\n').split(' '))
	return a, b, p

def init_point():
	print('Print point P')
	P = [int(input('P[x] = ')), int(input('P[y] = '))]
	return P

def check_input_point(P, a, b, p):	
	try:
		check_input_point(P, a, b, p)
	except:
		message = ['Please, try one more time','Your point is not on a curve given']
		print('\n'.join(message))
		P = init_point()
		check_input_point(P, a, b, p)
	else:
		return P

def check_input_point(P, a, b, p):
	assert (P[_sage_const_1 ]**_sage_const_2 ) % p == (P[_sage_const_0 ]**_sage_const_3  +a*P[_sage_const_0 ]+b) % p

def init_pass():
	print('Print numbers of Alice and Bob')
	A = int(input('Alice number is '))
	B = int(input('Bob number is '))
	return A, B

def gen_key(a, b, p, A, B, P):
	K1 = powP(P, A, a, b, p)
	K2 = powP(P, B,a, b, p)
	key = powP(K1, B, a, b, p)

	return key


def addP(P, Q, a, b, p):
	if P == []:
		if Q[_sage_const_1 ] == _sage_const_0 :
			R = Q
		else:
			R = [Q[_sage_const_0 ], -Q[_sage_const_1 ] % p]
	elif Q == []:
		if P[_sage_const_1 ] == _sage_const_0 :
			R = P
		else:
			R = [P[_sage_const_0 ], -P[_sage_const_1 ] % p]
	elif Q == P:
		if Q[_sage_const_1 ] == _sage_const_0 :
			R = []
		else:
			s = ((((_sage_const_3 *P[_sage_const_0 ]**_sage_const_2 ) % p + a) % p)/((_sage_const_2 *P[_sage_const_1 ])%p)) % p
			R = [(s**_sage_const_2  - P[_sage_const_0 ] - Q[_sage_const_0 ])%p]
			R.append((-_sage_const_1 *(P[_sage_const_1 ]+s*(R[_sage_const_0 ]-P[_sage_const_0 ])))%p)
	elif Q != P:
		if Q[_sage_const_0 ] == P[_sage_const_0 ]:
			R = []
		else:
			s = (((Q[_sage_const_1 ]-P[_sage_const_1 ])%p)/((Q[_sage_const_0 ]-P[_sage_const_0 ])%p))%p
			R = [(s**_sage_const_2  - P[_sage_const_0 ] - Q[_sage_const_0 ])%p]
			R.append((-_sage_const_1 *(P[_sage_const_1 ]+s*(R[_sage_const_0 ]-P[_sage_const_0 ])))%p)
	else:
		print('Bug')

	return R

def powP(P, k, a, b, p):
	R = copy(P)
	for i in range(k-_sage_const_1 ):
		R = addP(R, P, a, b, p)

	return R

def main():
	a, b, p = init_func()
	P = init_point()
	A, B = init_pass()
	key = gen_key(a, b, p, A, B, P)
	
	print(key)


if __name__ == '__main__':
	main()

